export const INDEX_PRODUCTS = 'INDEX_PRODUCTS'
export const INDEX_SALES = 'INDEX_SALES'
export const INDEX_ARRIVED_PRODUCTS = 'INDEX_ARRIVED_PRODUCTS'

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
export const SET_MIN_PRICE = 'SET_MIN_PRICE'
export const SET_MAX_PRICE = 'SET_MAX_PRICE'