development:
  adapter: postgresql
  encoding: unicode
  database: ibolit_development
  pool: 5
  username: postgres
  password: 'd1231'

test:
  adapter: postgresql
  encoding: unicode
  database: ibolit_test
  pool: 5
  username: postgres
  password: 'd1231'